import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Nokael Dash Logistics',
  description: 'Privacy Policy for Nokael Dash Logistics - Learn about how we collect, use, and protect your personal information.',
};

export default function PrivacyPolicy() {
  return (
    <div className="py-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold tracking-tight mb-8">Privacy Policy</h1>
          <p className="text-gray-600 dark:text-gray-400 mb-8">Last updated: May 27, 2025</p>

          <div className="prose dark:prose-invert max-w-none">
            <p className="mb-6">
              This Privacy Policy describes Our policies and procedures on the collection,
              use and disclosure of Your information when You use the Service and tells You
              about Your privacy rights and how the law protects You.
            </p>

            <p className="mb-6">
              We use Your Personal data to provide and improve the Service. By using the
              Service, You agree to the collection and use of information in accordance with
              this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6">Interpretation and Definitions</h2>

            <h3 className="text-xl font-bold mt-8 mb-4">Interpretation</h3>
            <p className="mb-6">
              The words of which the initial letter is capitalized have meanings defined
              under the following conditions. The following definitions shall have the same
              meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-bold mt-8 mb-4">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Nokael Dash Logistics LLC, 1 Airport road Abu Dhabi.</li>
              <li><strong>Country</strong> refers to: United Arab Emirates</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Application.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-bold mt-12 mb-6">Collecting and Using Your Personal Data</h2>

            <h3 className="text-xl font-bold mt-8 mb-4">Types of Data Collected</h3>

            <h4 className="text-lg font-bold mt-6 mb-4">Personal Data</h4>
            <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-bold mt-6 mb-4">Usage Data</h4>
            <p className="mb-6">
              Usage Data is collected automatically when using the Service. This may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6">Use of Your Personal Data</h2>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>For the performance of a contract</li>
              <li>To contact You</li>
              <li>To provide You with news, special offers and general information</li>
              <li>To manage Your requests</li>
              <li>For business transfers</li>
              <li>For other purposes</li>
            </ul>

            <h2 className="text-2xl font-bold mt-12 mb-6">Security of Your Personal Data</h2>
            <p className="mb-6">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6">Children's Privacy</h2>
            <p className="mb-6">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6">Changes to this Privacy Policy</h2>
            <p className="mb-6">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold mt-12 mb-6">Contact Us</h2>
            <p className="mb-6">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>By email: info@nokael.com</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
} 